apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-block-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: do-block-storage