version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword


  user_app:
    build:
      context: .
      # If the dockerfile is in the root directory and the docker-compose.yml is in a subdirectory, use:
      # context: ./code
      # If the dockerfile is in a subdirectory, use:
      # context: ./subdirectory
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres