# namespace
kind: Namespace
apiVersion: v1 
metadata:
  name: backend-team
---
# deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: backend-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aliabbaschadhar003/backend-pg:1
          ports:
          - containerPort: 3000
---
# Service
kind: Service 
apiVersion: v1
metadata:
  name: backend
  namespace: backend-team
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
  type: ClusterIP